### ISSUE TITLE
distribute is long deprecated

### ISSUE THREAD

**Issue by cwells** [51Degrees/Device-Detection#12]
The distribute package has been deprecated for quite some time.

In setup.py:

```python
install_requires=[
        'distribute',
]
```

Installation of distribute causes installation to fail on newer versions of pip/setuptools with `ImportError: No module named _markerlib`.

Probably this dependency should be changed to `setuptools`.

**Comment by Joseph51D** [comment]
Hi @cwells 

Thank you for bringing this to our attention. The current `distribute` package [wraps](https://pypi.python.org/pypi/distribute/0.7.3) `setuptools` which is why we have not seen fit to change it. However, as it is now potentially causing issues, we will look at patching it in our next release.

Regards,
Joe

**Comment by ben51degrees** [comment]
@cwells This issue has been closed in the latest release with commit 46c392b.

Regards,
Ben.
