### ISSUE TITLE
Crash php7.0 with installed module.

### ISSUE THREAD

**Issue by jackblackjack** [51Degrees/Device-Detection#28]
Hi,
I am trying to run php7 with builded module.

OS: Debian GNU/Linux 8.10 (jessie)
GCC version 4.9.2 
PHP 7.0

Module is installed is successfully.
But when run it with module gets same error:
> terminate called after throwing an instance of 'std::logic_error'
>   what():  basic_string::_S_construct null not valid
> Aborted

**Comment by JoshGrew51D** [comment]
Hi There 

Are you running this through the PHP CLI or Apache? 

What settings have you supplied within your php.ini file for 51Degrees?

**Comment by jackblackjack** [comment]
cli

extension=FiftyOneDegreesTrieV3.so
FiftyOneDegreesPatternV3.data_file=51Degrees-LiteV3.2.dat
FiftyOneDegreesPatternV3.property_list=BrowserName,BrowserVendor,BrowserVersion,DeviceType,HardwareVendor,IsTablet,IsMobile,IsCrawler,ScreenInchesDiagonal,ScreenPixelsWidth
FiftyOneDegreesPatternV3.cache_size=10000
FiftyOneDegreesPatternV3.pool_size=20

**Comment by JoshGrew51D** [comment]
This error will be thrown due to the fact you have referenced Pattern settings within the ini for a Hash module. When the settings are not available it will use the default values, which in this case, don't fully match. This is most likely down to there not being a .trie data file in the default file location.

You will need to use the following instead:
extension=FiftyOneDegreesTrieV3.so
FiftyOneDegreesTrieV3.data_file=path/to/51Degrees-LiteV3.2.trie
FiftyOneDegreesTrieV3.property_list=BrowserName,BrowserVendor,BrowserVersion,DeviceType,HardwareVendor,IsTablet,IsMobile,IsCrawler,ScreenInchesDiagonal,ScreenPixelsWidth

Both Cache and Pool size are not used with Hash as it utilises a different caching method.

Hash files are not included as part of our GitHub release but are available for download through our site by signing up for Lite or taking part in our Enterprise trial.

Let me know how you get on.

**Comment by JoshGrew51D** [comment]
You will need to change the 'Pattern' to 'Trie' in the data file and property list references.

**Comment by jackblackjack** [comment]
Change it.
Next level =)

call php -m
---------------
terminate called after throwing an instance of 'std::runtime_error'
  what():  The data is an unsupported version. Check you have the latest data and API.
Aborted
---------------
Which branch to get for the rebuild is compatible with the above parameters? Has builded is master branch.

**Comment by JoshGrew51D** [comment]
A different message is always progress 👍 

Your original build for the Hash module will work in master. Could you confirm the file size of your trie file, did you download from our site?

**Comment by jackblackjack** [comment]
Size of /opt/51Degrees-LiteV3.2.trie is 37268K

**Comment by JoshGrew51D** [comment]
The 2 things that pop out are the version number not being 3.4 for a 'trie' extension and the file size not matching up with what I would expect to see.

The Lite version of our Hash file when uncompressed should be around 143018KB, increasing slightly with each Enhanced version (Premium/Enterprise).

It is available for download as gzip so the first thing to check would be whether it needs decompressing.

**Comment by jackblackjack** [comment]
It's works
