### ISSUE TITLE
trie vs dat

### ISSUE THREAD

**Issue by ave-satan** [51Degrees/Device-Detection#30]
Hi there.

Just signed up for free version to try out trie database and for some reason the results differ vastly.
Used this UA to test against: `Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/70.0.3538.110 Safari/537.36`

`DETECTION_METHOD = 'v3-trie-wrapper'`:
```
{
 'AnimationTiming': 'True',
 'BlobBuilder': 'True',
 'BrowserName': 'Unknown',
 'BrowserPropertySource': 'RingMark',
 'BrowserVersion': 'Unknown',
 'Canvas': 'True',
 'CssBackground': 'True',
 'CssBorderImage': 'True',
 'CssCanvas': 'Unknown',
 'CssColor': 'True',
 'CssColumn': 'Unknown',
 'CssFlexbox': 'True',
 'CssFont': 'True',
 'CssImages': 'True',
 'CssMediaQueries': 'True',
 'CssMinMax': 'True',
 'CssOverflow': 'True',
 'CssPosition': 'True',
 'CssText': 'True',
 'CssTransforms': 'True',
 'CssTransitions': 'True',
 'CssUI': 'True',
 'DataSet': 'True',
 'DataUrl': 'True',
 'DeviceOrientation': 'True',
 'FileReader': 'True',
 'FileSaver': 'Unknown',
 'FileWriter': 'Unknown',
 'FormData': 'True',
 'Fullscreen': 'True',
 'GeoLocation': 'True',
 'History': 'True',
 'Html-Media-Capture': 'True',
 'Html5': 'True',
 'Id': '15364-18110-17470-18092',
 'Iframe': 'True',
 'IndexedDB': 'True',
 'IsEmulatingDesktop': 'False',
 'IsMobile': 'False',
 'JavascriptImageOptimiser': blablabla,
 'Json': 'True',
 'LayoutEngine': 'Unknown',
 'Masking': 'True',
 'Meter': 'Unknown',
 'PlatformName': 'Linux',
 'PlatformVersion': 'Unknown',
 'PostMessage': 'True',
 'Progress': 'True',
 'Promise': 'None',
 'Prompts': 'True',
 'ScreenPixelsHeight': 'Unknown',
 'ScreenPixelsHeightJavaScript': '',
 'ScreenPixelsWidth': 'Unknown',
 'ScreenPixelsWidthJavaScript': '',
 'Selector': 'True',
 'SupportsWebGL': 'Unknown',
 'Svg': 'True',
 'TouchEvents': 'True',
 'Track': 'True',
 'Video': 'True',
 'Viewport': 'True',
 'WebWorkers': 'True',
 'Xhr2': 'True'
}
```

And `DETECTION_METHOD = 'v3-wrapper'`:
```
{'AnimationTiming': 'True',
 'BlobBuilder': 'True',
 'BrowserName': 'Chrome',
 'BrowserPropertySource': 'Caniuse',
 'BrowserVersion': '70',
 'Canvas': 'True',
 'CssBackground': 'True',
 'CssBorderImage': 'False',
 'CssCanvas': 'False',
 'CssColor': 'True',
 'CssColumn': 'True',
 'CssFlexbox': 'True',
 'CssFont': 'True',
 'CssImages': 'False',
 'CssMediaQueries': 'True',
 'CssMinMax': 'True',
 'CssOverflow': 'True',
 'CssPosition': 'True',
 'CssText': 'True',
 'CssTransforms': 'True',
 'CssTransitions': 'True',
 'CssUI': 'True',
 'DataSet': 'True',
 'DataUrl': 'True',
 'DeviceOrientation': 'False',
 'Difference': 1,
 'FileReader': 'True',
 'FileSaver': 'Unknown',
 'FileWriter': 'Unknown',
 'FormData': 'True',
 'Fullscreen': 'False',
 'GeoLocation': 'True',
 'History': 'True',
 'Html-Media-Capture': 'True',
 'Html5': 'True',
 'Id': '15364-18110-86672-18092',
 'Iframe': 'True',
 'IndexedDB': 'True',
 'IsEmulatingDesktop': 'N/A',
 'IsMobile': 'False',
 'JavascriptImageOptimiser': blablabla,
 'Json': 'True',
 'LayoutEngine': 'Blink',
 'Masking': 'False',
 'MatchMethod': 3,
 'Meter': 'True',
 'PlatformName': 'Linux',
 'PlatformVersion': 'Unknown',
 'PostMessage': 'True',
 'Progress': 'True',
 'Promise': 'Full',
 'Prompts': 'True',
 'Rank': 7415,
 'ScreenPixelsHeight': 'Unknown',
 'ScreenPixelsHeightJavaScript': blablabla,
 'ScreenPixelsWidth': 'Unknown',
 'ScreenPixelsWidthJavaScript': blablabla,
 'Selector': 'True',
 'SupportsWebGL': 'True',
 'Svg': 'True',
 'TouchEvents': 'True',
 'Track': 'True',
 'Video': 'True',
 'Viewport': 'True',
 'WebWorkers': 'True',
 'Xhr2': 'True'
}
```

While the trie database works amazingly fast and it would be a great deal for some high load, it looks inferior in detecting some important stuff for me. More precisely, the browser info is missing.

Could you shed some light on this, please? Was it me misconfiguring or misusing something, maybe?

I'm using python 3.6

databases:
51Degrees-LiteV3.2.dat
51Degrees-LiteV3.4.trie

packages:
51degrees-mobile-detector==3.2.18.4
51degrees-mobile-detector-v3-trie-wrapper==3.2.18.4
51degrees-mobile-detector-v3-wrapper==3.2.18.4

script example:
```python
from fiftyone_degrees import mobile_detector
ua = 'Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/70.0.3538.110 Safari/537.36'
device = mobile_detector.match(ua)
```
the settings are left as is in default values, except database paths changed

**Comment by JoshGrew51D** [comment]
From taking a look at the User-Agent you linked in our database I can see this was added on the 22nd November. Both Lite data files that you are currently using were generated before this date.

This means that the detection will rely on the predictive capability of each algorithm to return the result. Hash is much faster due to the fact it will spend significantly less time attempting to find the closest match in the data file which is why they are different.

This is a design choice as Hash is aimed at users dealing with huge volumes of requests where getting back a result in the minimum time possible is a necessity. In this instance there is a slight trade off in accuracy for a huge increase in performance.

On the other hand, one thing that we always recommend people take advantage of with Pattern is our ability to flag when we are not confident with the result. 

If you take a look at our Match Metrics [example](https://51degrees.com/Developers/Documentation/APIs/Python-V32/Tutorials/Pattern/Match-Metrics) it will show you how you can pull the Method and Difference values from a match. A method of 'Exact' and Difference '0' would show we have seen that User-Agent before and are 100% sure that it what you are looking for. 

If the method is not `Exact` it will then split off into different results, which you can read more [here](https://51degrees.com/support/documentation/pattern) if you are interested, and difference will be > 0. The higher the number the less confident we are with the result.

Any questions just let me know.
