### ISSUE TITLE
The data file '51Degrees-LiteV4.1.hash' could not be found

### ISSUE THREAD

**Issue by LorenzoPantano** [51Degrees/Device-Detection#50]
Hi, 
I cloned the device-detection-cxx repository with:
`git clone --recurse-submodules https://github.com/51Degrees/device-detection-cxx.git`
and everything works fine.
Now when I try to reference the API from my C program. It gives me this error when I run the program:
`The data file '51Degrees-LiteV4.1.hash' could not be found. Check the file path and that the program has sufficient read permissions.`

I built the libraries with CMake, then added to the lib folder of my project and added it to my makefile.
I don't know why this happens, sorry but I'm new to programming in C, maybe I' doing this in the wrong way.
Thanks in advice.

**Comment by ben51degrees** [comment]
Hi,
That error comes from the 51Degrees library, so you have definitely included the library correctly. The issue could be one of 2 things:
 1. The data file has not been checked out from Git LFS. If you have successfully run the examples, then this is not the problem;
 2. the relative path to the data file is not correct, this can be fixed by either using the correct path relative to the executable, or using an absolute path instead.
Thanks,
Ben.
